### PR TITLE
fix: oneOf in sessions

### LINKED ISSUE #338: Try to use message instead of enum in oneOf

### PR DESCRIPTION
**Pull request by esoubiran-aneo**
Currently, the `oneOf` will generate this type in TS :

```ts
export interface AsObject {
  taskSummaryField: TaskSummaryField.AsObject;
  taskOptionField: TaskOptionField.AsObject;
  taskOptionGenericField?: TaskOptionGenericField.AsObject;
}
```

As you can see, `taskSummaryField` and `taskOptionField` are required, but `taskOptionGenericField` is optional. This is not what we want. We want to make  each field optional.

This occurs since we use `enum` directly in `oneOf` field. We should use a message instead.

This PR do this change and fix the issue. Now, generated code is :

```ts
export interface AsObject {
  taskSummaryField?: TaskSummaryField.AsObject;
  taskOptionField?: TaskOptionField.AsObject;
  taskOptionGenericField?: TaskOptionGenericField.AsObject;
}
```

fix #338

### CODE REVIEW

**Comment by esoubiran-aneo** [comment]
I'll do others PR to fix applications and tasks.

**Comment by aneojgurhem** [comment]
@esoubiran-aneo You need to update this one since I merged the new sort fields for listing sessions

**Review by esoubiran-aneo — COMMENTED** [review]
Update name in enum to have ENUM in name.

**Comment by esoubiran-aneo** [comment]
@aneojgurhem, it's fixed

**Review by melflitty — APPROVED** [review]

**Review by aneojgurhem — APPROVED** [review]

**Pull request merged**
