### PR TITLE
ci: release edge on tag

### PR DESCRIPTION
**Pull request by dbrasseur-aneo**
If the edge package to release should have been a normal release and not an edge package, prevents the publish edge from publishing

### CODE REVIEW

**Comment by esoubiran-aneo** [comment]
I'm not sur to understand the issue resolved by this PR.

**Comment by dbrasseur-aneo** [comment]
> I'm not sure to understand the issue resolved by this PR @dbrasseur-aneo .

Preventing this from happening again https://github.com/aneoconsulting/ArmoniK.Api/actions/runs/5389726555

**Comment by esoubiran-aneo** [comment]
> > I'm not sure to understand the issue resolved by this PR @dbrasseur-aneo .
> 
> Preventing this from happening again [aneoconsulting/ArmoniK.Api/actions/runs/5389726555](https://github.com/aneoconsulting/ArmoniK.Api/actions/runs/5389726555)

That's a commit on main so a release on main is something normal. I know that's this commit is made for a release but that's still a commit on main. Are we sure we want to add this complexity to check if there is a '-' in the version. Otherwire PR is correct.

**Comment by dbrasseur-aneo** [comment]
> > > I'm not sure to understand the issue resolved by this PR @dbrasseur-aneo .
> > 
> > 
> > Preventing this from happening again [aneoconsulting/ArmoniK.Api/actions/runs/5389726555](https://github.com/aneoconsulting/ArmoniK.Api/actions/runs/5389726555)
> 
> That's a commit on main so a release on main is something normal. I know that's this commit is made for a release but that's still a commit on main. Are we sure we want to add this complexity to check if there is a '-' in the version. Otherwire PR is correct.

Yes ! Because it created a full on release instead of an edga package ! Because we have a 3.9.0 and a 3.9.1 that are identical because of this problem

**Comment by esoubiran-aneo** [comment]
For the python release? for the other packages, it's based on a tag.

**Comment by dbrasseur-aneo** [comment]
> For the python release? for the other packages, it's based on a tag.

No even for csharp

**Comment by esoubiran-aneo** [comment]
> > For the python release? for the other packages, it's based on a tag.
> 
> No even for csharp

It could be an issue in the actions because of the usage of head_ref. We've talk with @aneojgurhem about this.

**Review by aneojgurhem — COMMENTED** [review]
I'm OK with the generation of the version once as this will prevent to produce inconsistent version if commits/tags are pushed between two steps.
However, the check can be performed once at the end of the version generation step. Everything depending on the generation step will not run. That is enough for what you want to achieve

**Review by aneojgurhem — APPROVED** [review]

**Pull request merged**
