### PR TITLE
feat: add health checks

### LINKED ISSUE #168: Add health check api
In order to know from the GUI if control_plane is still up, we need an health check. We can use API or the control_plane health check using http from the ingress. Waiting to know the better solution in #195

### PR DESCRIPTION
**Pull request by esoubiran-aneo**
fix #168

This will allow connected client to know is the API is up and running (so client can communicate with it) and if the cluter is up and running.

### CODE REVIEW

**Comment by esoubiran-aneo** [comment]
Could be achieved using ingress @lemaitre-aneo (using the core http health check) ?

**Comment by lemaitre-aneo** [comment]
This could be done via ingress only to have the health of the particuliar control plane pod your accessing. I think it is much better to have the health check embedded in the API.

**Comment by esoubiran-aneo** [comment]
> This could be done via ingress only to have the health of the particuliar control plane pod your accessing. I think it is much better to have the health check embedded in the API.

Yes, I agree!

**Review by lemaitre-aneo — DISMISSED** [review]

**Review by lemaitre-aneo — COMMENTED** [review]
You should add it to the mock

**Review by lemaitre-aneo — APPROVED** [review]

**Pull request merged**
